version: "3.9"

services:
  db:
    image: mariadb:10.5
    container_name: dashsql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dashboarddb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dashsql_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: ./viz
    container_name: dashsql_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=dashboarddb
      - DB_USER=user
      - DB_PASS=userpass
    depends_on:
      - db

volumes:
  db_data:
