version: "3.9"

services:
  mongo:
    image: danlimao/project_app:latest
    container_name: research_db_container
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db  # Named volume for persistent data storage
      - ./mongo-dump:/docker-entrypoint-initdb.d:ro  # Auto-import data on first run (read-only)
    networks:
      - internal_network
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  api:
    build:
      context: ./api
    container_name: api_service
    restart: always
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - mongo
    networks:
      - internal_network
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  streamlit:
    build:
      context: ./streamlit
    container_name: streamlit_service
    restart: always
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - api
    networks:
      - internal_network
    env_file:
      - .env
    environment:
      - API_BASE_URL=${API_BASE_URL}

volumes:
  mongodb_data:

networks:
  internal_network:
    driver: bridge