version: "3.9"

services:
  mongo:
    image: aymed/bdd-mongo:latest
    container_name: mongo_science
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_network

  api:
    build:
      context: ./api
    container_name: api_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - internal_network

  streamlit:
    build:
      context: ./streamlit
    container_name: streamlit_service
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - internal_network

volumes:
  mongo_data:

networks:
  internal_network:
    driver: bridge
